### ISSUE TITLE
Should not coerce ids by default

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm2obj#5]
Currently `opts.coerceIds` defaults to `true`. This is a bad thing, since 64-bit ids will break things because JavaScript stores numbers as 53-bits. The consequence will be string ids being converted to numbers rounded to the nearest number that can be represented in 53-bits.

We should switch this to false by default, and include a warning in the readme for using this option. The safest thing to do is leave ids as strings.

**Comment by hackergrrl** [comment]
Done. Merged in `v3.0.0`.
